install:
  - choco install pkgconfiglite 
  - appveyor-retry appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.14.1/gstreamer-1.0-devel-x86_64-1.14.1.msi
  - appveyor-retry appveyor DownloadFile https://gstreamer.freedesktop.org/data/pkg/windows/1.14.1/gstreamer-1.0-x86_64-1.14.1.msi
  - ps: msiexec /i gstreamer-1.0-x86_64-1.14.1.msi /quiet /qn /norestart /Lv  /log C:\install.log
  - ps: msiexec /i gstreamer-1.0-devel-x86_64-1.14.1.msi /quiet /qn /norestart /Lv  /log C:\install.log
  - cd/
  - dir /b/s *gstreamer*
